groups:
  - name: api-alerts
    rules:
    # Alerte sur le taux de requêtes réussies (sous 95%)
    - alert: APISuccessRateBelow95
      expr: sum(rate(http_requests_total{status=~"2.."}[5m])) / sum(rate(http_requests_total[5m])) < 0.95
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "API Success Rate Below 95%"
        description: "The API success rate has dropped below 95% for more than 5 minutes."

    # Alerte sur le taux de requêtes réussies (sous 70%)
    - alert: APISuccessRateBelow70
      expr: sum(rate(http_requests_total{status=~"2.."}[5m])) / sum(rate(http_requests_total[5m])) < 0.70
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "API Success Rate Below 70%"
        description: "The API success rate has dropped below 70% for more than 5 minutes."

    # Alerte sur le taux d'erreurs 4xx et 5xx (plus de 1%)
    - alert: APIErrorRateAbove1Percent
      expr: (sum(rate(http_requests_total{status=~"4.."}[5m])) + sum(rate(http_requests_total{status=~"5.."}[5m]))) / sum(rate(http_requests_total[5m])) > 0.01
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "API Error Rate Above 1%"
        description: "The API error rate (4xx and 5xx) has exceeded 1% for more than 5 minutes."
