global:
  scrape_interval: 15s  # Intervalle par défaut pour scraper les métriques
  evaluation_interval: 15s  # Intervalle pour évaluer les règles d'alertes

# Alerting rules configuration
rule_files:
  - "alert_rules.yml"  # Fichier contenant les règles d'alertes

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (Surveillance de l'hôte)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # PostgreSQL Exporter
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # MinIO Exporter
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  # FastAPI Application
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8080']

