{
 "title": "Stats Uploads documents",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total de documents uploads",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(documents_uploaded_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de chunks créés",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(chunks_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taille des fichiers téléchargés",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(upload_file_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de traitement des téléchargements de fichiers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(upload_processing_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}